import type {Metadata} from "next";
import "@fontsource-variable/vazirmatn";
import "./globals.css";
import "./ux-refresh.css";
import {Header} from "@/components/header";
import {Footer} from "@/components/footer";
import {PersianDigits} from "@/components/persian-digits";

const site=process.env.NEXT_PUBLIC_SITE_URL||"https://example.com";
const themeScript=`(()=>{try{const saved=localStorage.getItem("rtpmi-theme");const theme=saved==="dark"||saved==="light"?saved:(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme}catch{}})()`;
export const metadata:Metadata={metadataBase:new URL(site),title:{default:"رصدخانه ملی پرتال پژوهش و فناوری",template:"%s | رصدخانه پرتال پژوهش"},description:"مرجع داده‌محور ممیزی پرتال معاونت پژوهش و فناوری ۱۱۵ دانشگاه و مؤسسه دولتی مطابق ISC؛ شامل RTPMI، شواهد، اسناد و Open Data.",alternates:{canonical:"/"},openGraph:{title:"رصدخانه ملی پرتال پژوهش و فناوری — ISC ۱۱۵",description:"ممیزی شفاف ۱۱۵ پرتال، RTPMI ۴.۱، پرونده شواهد و داده باز",type:"website",locale:"fa_IR",url:"/"},twitter:{card:"summary_large_image",title:"رصدخانه ملی پرتال پژوهش و فناوری",description:"ISC ۱۱۵ · Evidence first · Open Data"},robots:{index:true,follow:true}};
const jsonLd={"@context":"https://schema.org","@type":"Dataset",name:"Iran Research & Technology Portal Observatory — ISC 115",description:"Evidence-based audit dataset for public Research & Technology Vice-Presidency portals of 115 Iranian public/government institutions in the ISC national classification.",url:site+"/datasets",dateModified:"2026-08-11",inLanguage:["fa","en"],isAccessibleForFree:true,license:"https://opensource.org/license/mit",creator:{"@type":"Organization",name:"Iran Research & Technology Portal Observatory"},distribution:[{"@type":"DataDownload",encodingFormat:"application/json",contentUrl:site+"/datasets/isc-institutions.json"},{"@type":"DataDownload",encodingFormat:"application/json",contentUrl:site+"/datasets/audit-deep-audit-matrix.json"},{"@type":"DataDownload",encodingFormat:"text/csv",contentUrl:site+"/datasets/statistics-portal-ranking.csv"}]};
export default function RootLayout({children}:{children:React.ReactNode}){const ld=JSON.stringify(jsonLd).replace(/</g,"\\u003c");return <html lang="fa" dir="rtl" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:themeScript}}/></head><body><PersianDigits/><a className="skipLink" href="#main-content">پرش به محتوای اصلی</a><Header/><div id="main-content">{children}</div><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:ld}}/></body></html>}
