import Link from "next/link";
import {formatFaNumber} from "@/lib/fa";

const dimensionLabels:any={portalIdentity:"هویت پرتال",organization:"ساختار",libraryDocuments:"کتابخانه",laboratories:"آزمایشگاه",industryTechnology:"صنعت و فناوری",informationTechnology:"فناوری اطلاعات",systemsServices:"سامانه‌ها",documentsRegulations:"اسناد"};

export function HeroConstellation({audits,summary}:{audits:any[];summary:any}){return <div className="constellation" aria-label="کهکشان شواهد ۱۱۵ دانشگاه"><div className="constellationHeader"><span><i/> نقشه زنده Evidence</span><b>۱۱۵ دانشگاه · ۸ بُعد</b></div><div className="constellationField">{audits.map((row,index)=>{const coverage=row.reviewEvidenceCoverage??row.auditEvidenceCoverage??0,x=7+((index*47)%87),y=8+((index*71)%82);const level=coverage>=75?"high":coverage>=50?"mid":coverage>0?"low":"dark";return <Link href={`/universities/${row.universitySlug}`} title={`${row.nameFa} — پوشش ${formatFaNumber(coverage)}٪`} className={`star ${level}`} style={{left:`${x}%`,top:`${y}%`,"--delay":`${(index%12)*-.22}s`} as React.CSSProperties} key={row.universitySlug}><i/><span>{coverage>=75?row.nameFa:""}</span></Link>})}<div className="constellationCore"><span>ماتریس ملی</span><b>{formatFaNumber(920)}</b><small>outcome مستند</small><em>{formatFaNumber(summary.ranked)} رتبه‌پذیر</em></div><div className="orbitLine one"/><div className="orbitLine two"/><div className="orbitLine three"/></div><div className="constellationFooter"><span><i className="high"/> پوشش ۷۵٪ و بیشتر</span><span><i className="mid"/> پوشش میانی</span><span><i className="low"/> شاهد اولیه</span><span><i className="dark"/> هنوز حل‌نشده</span><b>{formatFaNumber(summary.dimensionEvidenceOutcomes||920)} / {formatFaNumber(920)}</b></div></div>}

export function EvidenceSpectrum({dimensions}:{dimensions:Record<string,Record<string,number>>}){return <section className="spectrum"><header><div><span className="eyebrow">National evidence spectrum</span><h2>ضربان هشت بُعد شفافیت</h2></div><p>هر نوار دقیقاً ۱۱۵ دانشگاه را نشان می‌دهد؛ رنگ‌ها outcome ممیزی‌اند، نه نمره عملکرد دانشگاه.</p></header><div className="spectrumRows">{Object.entries(dimensions).map(([key,value],index)=>{const verified=value.verified||0,observed=value["observed-reference"]||0,restricted=value.restricted||0,unresolved=value.unresolved||0;return <div className="spectrumRow" key={key}><div className="spectrumLabel"><i>{String(index+1).padStart(2,"0")}</i><b>{dimensionLabels[key]}</b><span>{formatFaNumber(verified)} شاهد مستقیم</span></div><div className="spectrumBar" aria-label={`${dimensionLabels[key]}: ${verified} verified`}><i className="verified" style={{width:`${verified/1.15}%`}}/><i className="observed" style={{width:`${observed/1.15}%`}}/><i className="restricted" style={{width:`${restricted/1.15}%`}}/><i className="unresolved" style={{width:`${unresolved/1.15}%`}}/></div><strong>{formatFaNumber(Math.round(verified/1.15))}<small>%</small></strong></div>})}</div><footer><span><i className="verified"/>تأیید مستقیم</span><span><i className="observed"/>شاهد/ارجاع</span><span><i className="restricted"/>دسترسی محدود</span><span><i className="unresolved"/>حل‌نشده</span></footer></section>}

export function RankPodium({rankings}:{rankings:any[]}){const first=rankings.slice(0,3);const ordered=[first[1],first[0],first[2]].filter(Boolean);return <section className="podiumStory"><header><div><span className="eyebrow">RTPMI portal podium</span><h2>سه پرتال پیشرو در این Snapshot</h2></div><p>ارتفاع ستون از امتیاز بلوغ پرتال می‌آید؛ اندازه دانشگاه یا کیفیت علمی را نمایش نمی‌دهد.</p></header><div className="podiumStage">{ordered.map((row,index)=>{const place=index===1?1:index===0?2:3;return <Link href={`/universities/${row.universitySlug}`} className={`podium place${place}`} key={row.universitySlug}><div className="podiumPerson"><span>{row.nameFa}</span><small>اطمینان {formatFaNumber(row.confidence)}٪</small><b>{formatFaNumber(row.score)}</b></div><div className="podiumColumn" style={{height:`${120+row.score*1.25}px`}}><i>{formatFaNumber(place)}</i><span>RTPMI</span></div></Link>})}<div className="podiumAura"/></div></section>}
