import Link from "next/link";
import {rankings} from "@/lib/data";
import {metricMethods, rankingGate, scoringStages, weightPercent} from "@/lib/rtpmi-methodology";

export const metadata={title:"روش‌شناسی RTPMI ۴.۲ | ISC ۱۱۵",description:"فرمول، قواعد شواهد و روش رتبه‌بندی بلوغ پرتال معاونت پژوهشی و فناوری، مستقل از رتبه عملکردی ISC."};

export default function Page(){
  const example:any=rankings[0];
  return <main className="shell page methodologyPage">
    <header className="pageHero"><div><span className="kicker">RTPMI 4.2 / OPEN & REPRODUCIBLE</span><h1>هر رتبه باید تا شاهد و فرمول قابل ردیابی باشد.</h1><p>RTPMI کیفیت، شفافیت و یافت‌پذیری سطح عمومی پرتال معاونت پژوهشی و فناوری را می‌سنجد؛ نه کیفیت علمی یا عملکرد پژوهشی کل دانشگاه.</p></div><div className="pageHeroStamp"><b>۸</b><span>مؤلفه نمره‌دهی</span><small>بر پایه ۷ بُعد شواهد عمومی</small></div></header>

    <section className="methodFlow" aria-labelledby="method-flow-title"><header><span className="eyebrow">Evaluation path</span><h2 id="method-flow-title">مسیر ارزیابی از URL تا رتبه</h2></header><div>{scoringStages.map(stage=><article key={stage.number}><i>{stage.number}</i><b>{stage.title}</b><p>{stage.text}</p></article>)}</div></section>

    <section className="methodSection"><div className="sectionHead"><div><span className="eyebrow">Metric rules · 0—100</span><h2>در هر مؤلفه چه چیزی شمرده می‌شود؟</h2></div><p>فقط اقلامی وارد محاسبه می‌شوند که evidence پذیرفته‌شده دارند. سقف هر مؤلفه ۱۰۰ است و وزن آن فقط در مرحله ترکیب اعمال می‌شود.</p></div><div className="metricMethodGrid">{metricMethods.map(method=><article key={method.key}><header><span>{method.label}</span><b>{weightPercent(method.weight)}</b></header><p>{method.evaluation}</p><footer><span>شرط نمره کامل</span><b>{method.fullScore}</b></footer></article>)}</div></section>

    <section className="calculationSheet"><div><span className="eyebrow">Calculation</span><h2>نمره، اطمینان و رتبه سه چیز متفاوت‌اند</h2><dl><div><dt>نمره RTPMI</dt><dd>Σ (نمره مؤلفه × وزن) ÷ Σ وزن مؤلفه‌های فعال</dd></div><div><dt>Confidence</dt><dd>۷۲٪ پوشش Audit Evidence + ۲۸٪ کامل‌بودن منبع و تاریخ Provenance</dd></div><div><dt>دروازه انتشار</dt><dd><code>{rankingGate.portalAuditStatus}</code> + پوشش حداقل {rankingGate.minimumAuditEvidenceCoverage.toLocaleString("fa-IR")}٪ + اطمینان حداقل {rankingGate.minimumConfidence.toLocaleString("fa-IR")}٪</dd></div><div><dt>شکستن تساوی</dt><dd>ابتدا نمره بالاتر، سپس Confidence بالاتر و در پایان رتبه ISC پایین‌تر.</dd></div></dl></div><aside><span>قاعده داده گمشده</span><b>unresolved ≠ 0</b><p>بُعد حل‌نشده از مخرج وزن فعال حذف می‌شود. در عوض پوشش و Confidence افت می‌کند و ممکن است دانشگاه اصلاً رتبه‌پذیر نشود.</p></aside></section>

    {example?<section className="workedExample"><header><div><span className="eyebrow">Worked example · snapshot جاری</span><h2>رد محاسبه یک پرتال واقعی</h2></div><Link href={`/universities/${example.universitySlug}`}>پرونده {example.nameFa} ←</Link></header><div className="exampleSummary"><article><span>وزن فعال</span><b>{example.activeWeight.toLocaleString("fa-IR")}٪</b></article><article><span>نمره وزنی</span><b>{example.score.toLocaleString("fa-IR")}</b></article><article><span>Confidence</span><b>{example.confidence.toLocaleString("fa-IR")}٪</b></article><article><span>رتبه منتشرشده</span><b>#{example.rank.toLocaleString("fa-IR")}</b></article></div><div className="exampleMetrics">{metricMethods.map(method=><div key={method.key}><span>{method.label} · وزن {weightPercent(method.weight)}</span><b>{example.metrics[method.key]?.toLocaleString("fa-IR")??"نامشخص"}</b></div>)}</div><p>این مثال از Snapshot جاری خوانده می‌شود؛ بنابراین با بازتولید داده، مثال و جدول رتبه هم‌زمان تغییر می‌کنند.</p></section>:null}

    <article className="glass prose methodNotes"><h2>دامنه و مرز تفسیر</h2><p>هر ۱۱۵ نهاد دولتی طبقه‌بندی ملی ISC سال ۱۴۰۲–۱۴۰۱ در محصول حضور دارد: ۶۹ جامع، ۲۴ صنعتی، ۴ علوم کشاورزی، ۴ هنر، ۴ زیرنظام و ۱۰ دستگاه اجرایی. نهادهای غیردولتی و علوم پزشکی خارج از Scope هستند.</p><h3>هفت بُعد Evidence</h3><p>هویت پرتال معاونت پژوهشی و فناوری، ساختار سازمانی، کتابخانه و اسناد، آزمایشگاه‌ها، صنعت و فناوری، سامانه‌ها و خدمات، و اسناد و مقررات؛ در مجموع ۸۰۵ outcome مستقل.</p><h3>ISC Rank ≠ RTPMI</h3><p>رتبه ISC جایگاه مؤسسه در طبقه‌بندی ملی ISC است. RTPMI شاخص اختصاصی این پروژه برای بلوغ پرتال عمومی معاونت پژوهشی و فناوری است. جایگاه‌های بین‌المللی نیز سنجه‌ای جدا هستند و وارد فرمول RTPMI نمی‌شوند.</p><h3>بازتولید</h3><p>اجرای <code>npm run prepare:data</code> ماتریس ۱۱۵×۷، رتبه RTPMI، Provenance Ledger، Open Data، ۱۱۵ Audit Packet و CSVها را از داده نسخه‌بندی‌شده دوباره می‌سازد.</p></article>
  </main>;
}
