import {notFound} from "next/navigation";
import Link from "next/link";
import {ShareButton} from "@/components/share-button";
import {institutions,audits,deepAudits,rankings,unitCatalog,systemCatalog,documentCatalog} from "@/lib/data";

export function generateStaticParams(){return institutions.map(x=>({slug:x.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const u:any=institutions.find(x=>x.slug===slug);return{title:u?`${u.nameFa} | پرونده پرتال پژوهش`:"دانشگاه",description:u?`پرونده ممیزی پرتال پژوهش و فناوری ${u.nameFa}، وضعیت شواهد، RTPMI، واحدها، سامانه‌ها و اسناد.`:""}}
const labels:any={portalIdentity:"هویت پرتال",organization:"ساختار سازمانی",libraryDocuments:"کتابخانه و اسناد",laboratories:"آزمایشگاه‌ها",industryTechnology:"صنعت و فناوری",informationTechnology:"فناوری اطلاعات",systemsServices:"سامانه‌ها و خدمات",documentsRegulations:"اسناد و مقررات"};
const states:any={verified:"تأیید مستقیم",'observed-reference':"شاهد/ارجاع",restricted:"دسترسی محدود",unresolved:"هنوز حل نشده"};
const metricLabels:any={documents:"اسناد",organization:"ساختار",library:"کتابخانه",laboratories:"آزمایشگاه",digital:"دیجیتال و IT",industryTech:"صنعت و فناوری",dataQuality:"کیفیت داده",findability:"یافت‌پذیری"};

export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const u:any=institutions.find(x=>x.slug===slug);if(!u)notFound();const a:any=audits.find(x=>x.universitySlug===slug);const m:any=deepAudits.find(x=>x.universitySlug===slug);const r:any=rankings.find(x=>x.universitySlug===slug);const units:any[]=unitCatalog.filter(x=>x.universitySlug===slug);const systems:any[]=systemCatalog.filter(x=>x.universitySlug===slug);const documents:any[]=documentCatalog.filter(x=>x.universitySlug===slug);const verified=Object.values(m.dimensions).filter(x=>x==="verified").length;return <main className="shell page profilePage">
  <nav className="breadcrumbs" aria-label="مسیر صفحه"><Link href="/universities">دانشگاه‌ها</Link><span>/</span><span>{u.nameFa}</span></nav>
  <header className="profileHero"><div><div className="profileMeta"><span>{u.category}</span><span>رتبه ISC {u.iscRank.toLocaleString("fa-IR")}</span><span>آخرین ممیزی {new Date(a.auditDate).toLocaleDateString("fa-IR")}</span></div><h1>{u.nameFa}</h1><p>پرونده مستند اکوسیستم عمومی معاونت پژوهش و فناوری. جایگاه ISC و RTPMI دو سنجه مستقل‌اند.</p><div className="profileActions">{a.researchUrl?<a className="primaryAction" href={a.researchUrl} target="_blank" rel="noopener noreferrer">باز کردن پرتال رسمی ↗</a>:<span className="disabledAction">پرتال مستقیم هنوز تأیید نشده</span>}<ShareButton title={`پرونده پرتال پژوهش ${u.nameFa}`}/><a href={`/datasets/audit-packets/${slug}.json`}>دریافت پرونده JSON ↓</a></div></div><div className={r?"profileScore":"profileScore unranked"}>{r?<><span>RTPMI 4.1</span><b>{r.score}</b><div><small>رتبه ملی پرتال</small><strong>#{r.rank.toLocaleString("fa-IR")}</strong></div><div><small>سطح اطمینان</small><strong>{r.confidence}%</strong></div></>:<><span>وضعیت RTPMI</span><b>—</b><strong>رتبه منتشر نشده</strong><small>Evidence برای نمره عمومی کافی نیست.</small></>}</div></header>
  <section className="profileSnapshot"><div><span>وضعیت پرتال</span><b>{a.portalAuditStatus==="direct-official"?"مستقیم و رسمی":a.portalAuditStatus.includes("restricted")?"دسترسی محدود":"ارجاع/شاهد ثبت‌شده"}</b></div><div><span>پوشش شواهد</span><b>{m.auditEvidenceCoverage}%</b><i><em style={{width:`${m.auditEvidenceCoverage}%`}}/></i></div><div><span>ابعاد تأیید مستقیم</span><b>{verified.toLocaleString("fa-IR")} از ۸</b></div><div><span>اقلام فهرست‌شده</span><b>{(units.length+systems.length+documents.length).toLocaleString("fa-IR")}</b><small>{units.length} واحد · {systems.length} سامانه · {documents.length} سند</small></div></section>
  <section className="section"><div className="sectionHead"><div><span className="eyebrow">Evidence map · 8 dimensions</span><h2>وضعیت اکوسیستم در یک نگاه</h2></div><p>رنگ خاکستری یعنی داده عمومی هنوز حل نشده؛ هیچ‌گاه به معنی نبود آن واحد یا عملکرد صفر نیست.</p></div><div className="dimensionGrid">{Object.entries(m.dimensions).map(([key,value]:any)=><div className={`dimensionCard ${value}`} key={key}><div><i/><span>{states[value]}</span></div><b>{labels[key]}</b><small>{value==="verified"?"شاهد مستقیم در Snapshot":value==="observed-reference"?"نشانه‌ای ثبت شده، رابطه قطعی نیست":value==="restricted"?"راستی‌آزمایی عمومی محدود است":"در صف تکمیل Evidence"}</small></div>)}</div></section>
  {r&&<section className="section rtpmiSection"><div className="sectionHead"><div><span className="eyebrow">RTPMI DNA · active weights</span><h2>پروفایل بلوغ پرتال</h2></div><p>مقدار نامشخص از مخرج وزن فعال حذف و باعث کاهش Confidence شده است.</p></div><div className="metricGrid">{Object.entries(r.metrics).map(([key,value]:any)=><div className={value===null?"metricCard missing":"metricCard"} key={key}><div><span>{metricLabels[key]}</span><b>{value===null?"نامشخص":value}</b></div><i><em style={{width:`${value??0}%`}}/></i></div>)}</div></section>}
  <section className="section evidenceStory"><div className="evidenceSummary"><span className="eyebrow">Audit note</span><h2>این نتیجه بر چه اساسی ثبت شده؟</h2><p>{a.note}</p><div className="evidenceUrls">{(a.evidenceUrls||[]).map((url:string)=><a href={url} key={url} target="_blank" rel="noopener noreferrer"><span>منبع رسمی</span><b>{url}</b><i>↗</i></a>)}</div>{!a.evidenceUrls?.length&&<div className="noEvidence">در Snapshot فعلی URL مستقیم قابل انتشار ثبت نشده است. این وضعیت برای تکمیل دوره بعد نگه‌داری می‌شود.</div>}</div><aside><b>{m.auditEvidenceCoverage}%</b><span>Audit Evidence Coverage</span><p>این عدد میزان حل‌شدن Evidence است، نه امتیاز کیفیت علمی یا عملکرد دانشگاه.</p><Link href="/methodology">قواعد تفسیر داده ←</Link></aside></section>
  <section className="section catalogSection"><div className="sectionHead"><div><span className="eyebrow">Public ecosystem catalog</span><h2>واحدها، سامانه‌ها و اسناد ثبت‌شده</h2></div><p>فقط اقلامی نمایش داده می‌شوند که ردّ منبع آن‌ها در داده وجود دارد.</p></div><div className="catalogGrid"><Catalog title="واحدها و زیرمجموعه‌ها" count={units.length} items={units} empty="واحد تأییدشده‌ای در Snapshot ثبت نشده است."/><Catalog title="سامانه‌ها و خدمات" count={systems.length} items={systems} empty="سامانه تأییدشده‌ای در Snapshot ثبت نشده است."/><Catalog title="اسناد و مقررات" count={documents.length} items={documents} empty="سند مستقیم تأییدشده‌ای در Snapshot ثبت نشده است."/></div></section>
</main>}

function Catalog({title,count,items,empty}:{title:string;count:number;items:any[];empty:string}){return <div className="catalogCard"><header><h3>{title}</h3><b>{count.toLocaleString("fa-IR")}</b></header>{items.length?<div>{items.map(item=>{const url=item.url||item.sourceUrl;return <a href={url||undefined} target={url?"_blank":undefined} rel={url?"noopener noreferrer":undefined} key={item.id}><span><b>{item.nameFa||item.title}</b><small>{item.type||item.category||item.status}</small></span>{url&&<i>↗</i>}</a>})}</div>:<p>{empty}<small>نامشخص ≠ وجود ندارد</small></p>}</div>}
