import fs from "node:fs";import path from "node:path";const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const isc=read("data/isc/institutions.json"),source=read("data/isc/source.json"),audit=read("data/audit/portal-audit.json"),deep=read("data/audit/deep-audit-matrix.json"),rank=read("data/statistics/portal-ranking.json"),units=read("data/units/catalog.json"),systems=read("data/systems/catalog.json"),docs=read("data/documents/catalog.json"),packets=read("data/audit/packets-index.json"),ledger=read("data/evidence/provenance-ledger.json");
const cats={جامع:69,صنعتی:24,"علوم کشاورزی":4,هنر:4,زیرنظام:4,"دستگاه اجرایی":10};
if(isc.length!==115)throw Error(`ISC scope must be 115, got ${isc.length}`);if(source.publicInstitutions!==115)throw Error('ISC source metadata count mismatch');for(const [k,n] of Object.entries(cats)){const c=isc.filter(x=>x.category===k).length;if(c!==n)throw Error(`${k}: ${c} != ${n}`);if(source.categories?.[k]!==n)throw Error(`source category ${k} mismatch`)}
const slugs=isc.map(x=>x.slug),valid=new Set(slugs);if(valid.size!==115)throw Error('Duplicate ISC slug');
for(const [name,collection] of [['Audit',audit],['Deep audit',deep],['Packet index',packets]])if(collection.length!==115||new Set(collection.map(x=>x.universitySlug??x.slug)).size!==115)throw Error(`${name} must cover unique 115 ISC institutions`);
for(const collection of [audit,deep,units,systems,docs])for(const x of collection)if(!valid.has(x.universitySlug))throw Error(`Record outside ISC: ${x.universitySlug}`);
const unresolved=audit.filter(x=>x.portalAuditStatus==='unresolved-public-portal');if(unresolved.length)throw Error(`Portal-resolution outcome still missing for: ${unresolved.map(x=>x.universitySlug).join(',')}`);
const packetDir='data/audit/packets';const packetFiles=fs.readdirSync(packetDir).filter(x=>x.endsWith('.json'));if(packetFiles.length!==115)throw Error(`Expected 115 packet files, got ${packetFiles.length}`);for(const slug of valid)if(!fs.existsSync(path.join(packetDir,`${slug}.json`)))throw Error(`Missing audit packet: ${slug}`);
const A=new Map(audit.map(x=>[x.universitySlug,x])),M=new Map(deep.map(x=>[x.universitySlug,x]));for(const r of rank){if(!valid.has(r.universitySlug))throw Error(`Rank outside ISC: ${r.universitySlug}`);if(A.get(r.universitySlug)?.portalAuditStatus!=='direct-official')throw Error(`Rank without direct portal: ${r.universitySlug}`);if((M.get(r.universitySlug)?.auditEvidenceCoverage??0)<75)throw Error(`Rank below audit coverage gate: ${r.universitySlug}`);if(r.confidence<65)throw Error(`Low-confidence numeric rank: ${r.universitySlug}`);if(!Number.isFinite(r.score)||r.score<0||r.score>100)throw Error(`Invalid RTPMI: ${r.universitySlug}`)}
for(const x of [...units,...systems,...docs]){if(['verified','verified-basic'].includes(x.evidence)&&!x.sourceUrl&&!x.parentUrl&&!x.url)throw Error(`Evidence record without provenance URL: ${x.id}`)}
const ids=[...units,...systems,...docs].map(x=>x.id);if(new Set(ids).size!==ids.length)throw Error('Duplicate entity id across catalogs');
for(const x of ledger){if(!valid.has(x.universitySlug))throw Error(`Provenance outside ISC: ${x.universitySlug}`);if(!x.sourceUrl)throw Error(`Provenance without sourceUrl: ${x.id}`)}
const requiredCsv=['data/isc/institutions.csv','data/audit/portal-audit.csv','data/audit/deep-audit-matrix.csv','data/audit/packets-index.csv','data/statistics/portal-ranking.csv','data/units/catalog.csv','data/systems/catalog.csv','data/documents/catalog.csv'];for(const f of requiredCsv)if(!fs.existsSync(f))throw Error(`Missing CSV export: ${f}`);
console.log(`ISC 115/115 | portal outcome 115/115 | unresolved outcome 0 | deep matrix 115/115 | packets 115/115 | ranked ${rank.length} | unranked ${115-rank.length} | units ${units.length} | systems ${systems.length} | docs ${docs.length} | provenance ${ledger.length}`);
